openapi: 3.0.1
info:
  title: API REST Node
  description: API REST Node
  termsOfService: ''
  contact:
    email: jgonzalez@teceng-gaming.com.ar
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: ''
servers:
  - url: 'http://localhost:8080'
  - url: ''
tags:
  - name: counter
    description: Counters managment
    externalDocs:
      description: ''
      url: ''
  - name: event
    description: Event managment
  - name: user
    description: Operations about user
    externalDocs:
      description: ''
      url: ''
paths:
  /counter:
    post:
      tags:
        - counter
      summary: Envío de contadores
      operationId: addCounter
      requestBody:
        description: Agregado de un nuevo contador
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Counter'
          application/xml:
            schema:
              $ref: '#/components/schemas/Counter'
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Counter'
              example:
                egmiid : 17
                ci: 350
                co: 10
                jp: 200
                jj: 10
                drop: 0
                cc: 0
                fecha: "2019-11-04T18:15:32.673Z"  
                sala_id: 7
        '405':
          description: Invalid input
          content: {}
        '401':
          description: Invalid token
          content: {}
      security:
        - bearerAuth: []
      x-codegen-request-body-name: body
    get:
      tags:
        - counter
      summary: Obtención de contadores
      description: ''
      operationId: getCounter
      parameters:
        - name: fecha_desde
          in: query
          description: Desde esta fecha
          required: true
          style: form
          explode: true
          schema:
            type: string
            items:
              type: string
        - name: fecha_hasta
          in: query
          description: Hasta esta fecha
          required: true
          style: form
          explode: true
          schema:
            type: string
            items:
              type: string
        - name: egmid
          in: query
          description: ID de EGM
          required: false
          style: form
          explode: true
          schema:
            type: integer
            items:
              type: integer
      responses:
        '200':
          description: successful operation
          content:
            # application/xml:
            #   schema:
            #     type: array
            #     items:
            #       $ref: '#/components/schemas/Counter'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Counter'
              example:
                  _id: "5dbc7cec1fa73877d5e4c7c7"
                  egmiid : 17
                  ci: 350
                  co: 10
                  jp: 200
                  jj: 10
                  drop: 0
                  cc: 0
                  fecha: "2019-11-04T18:15:32.673Z"  
                  sala_id: 7
                  __v: 0
        '400':
          description: Invalid status value
          content: {}
        '401':
          description: Invalid token
          content: {}
      security:
        - bearerAuth: []
  /event:
    get:
      tags:
        - event
      summary: Consulta de eventos
      description: ''
      operationId: getEvent
      parameters:
        - name: fecha_desde
          in: query
          description: Desde esta fecha
          required: true
          style: form
          explode: true
          schema:
            type: string
            items:
              type: string
        - name: fecha_hasta
          in: query
          description: Hasta esta fecha
          required: true
          style: form
          explode: true
          schema:
            type: string
            items:
              type: string
        - name: egmid
          in: query
          description: ID de EGM
          required: false
          style: form
          explode: true
          schema:
            type: integer
            items:
              type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
              example:
                  _id: "5dbc7cec1fa73877d5e4c7c7"
                  egmiid : 444
                  fecha: "2019-11-04T18:15:32.673Z"  
                  sala_id: 7
                  codigo_evento: "AAA999"
                  __v: 0  
                # additionalProperties:
                #   type: integer
                #   format: int32
        '401':
          description: Invalid token
          content: {}
      security:
        - bearerAuth: []
    post:
      tags:
        - event
      summary: Envío de eventos
      operationId: addEvent
      requestBody:
        description: Agregado de un nuevo evento
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
          # application/xml:
          #   schema:
          #     $ref: '#/components/schemas/Event'
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                example:
                  _id: "5dbc7cec1fa73877d5e4c7c7"
                  egmiid : 444
                  fecha: "2019-11-04T18:15:32.673Z"  
                  sala_id: 7
                  codigo_evento: "AAA999"
                  __v: 0  
        '405':
          description: Invalid input
          content: {}
        '401':
          description: Invalid token
          content: {}
      x-codegen-request-body-name: body
      security:
        - bearerAuth: []
  /user:
    post:
      tags:
        - user
      summary: Crear Usuario
      description: ''
      operationId: addUser
      requestBody:
        description: Crea un Usuario
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          # application/xml:
          #   schema:
          #     $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                example:
                  _id: "5dbc7cec1fa73877d5e4c7c7"
        '405':
          description: Invalid input
          content: {}
        '401':
          description: Invalid token
          content: {}
      x-codegen-request-body-name: body
      security:
        - bearerAuth: []
  /user/login:
    post:
      tags:
        - user
      summary: Login de usuario en el sistema
      operationId: loginUser
      requestBody:
        description: Logea a un Usuario
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
          # application/xml:
          #   schema:
          #     $ref: '#/components/schemas/UserLogin'
        required: true
      responses:
        '200':
          description: successful operation
          content:
            # application/xml:
            #   schema:
            #     type: string
            #     items:
            #       $ref: '#/components/schemas/User'
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/User'
              example:
                token : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoiamRpZWd1ZXoiLCJpYXQiOjE1NzI4OTEyNDAsImV4cCI6MTU3Mjk3NzY0MH0.cQO0tmFMyWBZEiJ65pkmV8K9Rb5wFBLET03sk4w96xk"

        '400':
          description: Invalid username/password supplied
          content: {}
  /user/login/simetrico:
    post:
      tags:
        - user
      summary: Login de usuario con ecriptacion simetrica
      operationId: loginUserSymm
      requestBody:
        description: Logea a un usuario con ecriptacion simetrica
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginSymm'
          # application/xml:
          #   schema:
          #     $ref: '#/components/schemas/UserLogin'
        required: true
      responses:
        '200':
          description: successful operation
          content:
            # application/xml:
            #   schema:
            #     type: string
            #     items:
            #       $ref: '#/components/schemas/User'
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/UserLoginSymm'
              example:
               token : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoiamRpZWd1ZXoiLCJpYXQiOjE1NzI4OTEyNDAsImV4cCI6MTU3Mjk3NzY0MH0.cQO0tmFMyWBZEiJ65pkmV8K9Rb5wFBLET03sk4w96xk"

        '400':
          description: Invalid username/password supplied
          content: {}
  /user/login/asimetrico:
    post:
      tags:
        - user
      summary: Login de usuario con ecriptacion asimetrica
      operationId: loginUserAsymm
      requestBody:
        description: Logea a un usuario con ecriptacion asimetrica
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginAsymm'
          # application/xml:
          #   schema:
          #     $ref: '#/components/schemas/UserLogin'
        required: true
      responses:
        '200':
          description: successful operation
          content:
            # application/xml:
            #   schema:
            #     type: string
            #     items:
            #       $ref: '#/components/schemas/User'
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/UserLoginAsymm'
              example:
               token : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoiamRpZWd1ZXoiLCJpYXQiOjE1NzI4OTEyNDAsImV4cCI6MTU3Mjk3NzY0MH0.cQO0tmFMyWBZEiJ65pkmV8K9Rb5wFBLET03sk4w96xk"

        '400':
          description: Invalid username/password supplied
          content: {}        
components:
  schemas:
    User:
      type: object
      properties:
        nombre:
          type: string
        apellido:
          type: string
        usuario:
          type: string
          pattern: '^[a-zA-Z][A-Za-z0-9]+$'
        password:
          type: string
          pattern: '^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$'
        status:
          type: boolean
        fecha_alta:
          type: string
          format: date-time
        public_key:
          type: string
          format: byte
      xml:
        name: User
    Counter:
      type: object
      properties:
        egmid:
          type: integer
          format: int64
        ci:
          type: integer
          minimum: 0
          exclusiveMinimum: false
          maximum: 1000000000000000000
          exclusiveMaximum: true
        co:
          type: integer
          format: int64
          maximum: 1000000000000000000
          exclusiveMaximum: true
        jp:
          type: integer
          format: int64
          maximum: 1000000000000000000
          exclusiveMaximum: true
        jj:
          type: integer
          format: int64
          maximum: 1000000000000000000
          exclusiveMaximum: true
        drop:
          type: integer
          format: int64
          maximum: 1000000000000000000
          exclusiveMaximum: true
        cc:
          type: integer
          format: int64
          maximum: 1000000000000000000
          exclusiveMaximum: true
        fecha:
          type: string
          format: date-time
        sala_id:
          type: integer
          format: int64
      xml:
        name: User
    Event:
      type: object
      properties:
        egmid:
          type: integer
          format: int64
        fecha:
          type: string
          format: date-time
        sala_id:
          type: integer
          format: int64
        codigo_evento:
          type: string
          pattern: '^[a-fA-F0-9]+$'
        # xml:
        #   name: Event  
    UserLogin:
      type: object
      properties:
        usuario:
          type: string
          pattern: '^[a-zA-Z][A-Za-z0-9]+$'
        password:
          type: string
          pattern: '^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$'
        # xml:
        #   name: UserLogin
    UserLoginSymm:
      type: object
      properties:
        usuario:
          type: string
          pattern: '^[a-zA-Z][A-Za-z0-9]+$'
        signature:
          type: object
      example:
        usuario: 'yo4'
        signature: {"iv":"4c3e19b759e7aefea809e15e5542cb27","encryptedData":"202c4cfd81f1e7bf7b18621c5e12e77e66fed5badde2d9683888214b215f5ad0"}
    UserLoginAsymm:
      type: object
      properties:
        usuario:
          type: string
          pattern: '^[a-zA-Z][A-Za-z0-9]+$'
        signature:
          type: object
      example:
        usuario: 'yo4'
        signature: {"type":"Buffer","data":[32,252,135,208,110,167,148,154,188,78,198,120,202,239,253,204,234,143,229,126,147,20,99,50,39,55,193,148,76,123,240,159,136,171,151,64,10,224,193,52,159,68,228,160,5,72,13,51,58,229,56,238,144,97,237,6,8,168,33,81,133,163,53,138,247,28,73,23,10,166,98,47,104,147,95,40,244,252,217,127,41,150,117,101,32,55,63,83,102,130,179,178,166,41,196,49,104,66,187,88,93,22,172,169,42,161,65,119,132,198,102,172,179,243,239,202,218,214,106,161,131,132,230,54,27,216,223,35,250,177,30,223,16,182,77,77,219,143,107,148,66,162,179,220,1,141,233,197,113,239,240,219,149,184,28,76,84,244,88,14,236,171,9,132,180,199,37,22,140,75,67,7,241,152,38,165,181,70,1,13,232,174,63,176,224,171,98,216,115,225,131,177,250,12,183,34,85,235,174,85,105,143,12,197,39,73,104,95,155,176,1,91,225,75,5,237,205,52,92,171,36,250,150,174,227,156,193,237,104,64,31,94,187,97,105,63,148,249,232,148,121,240,64,194,95,111,239,25,92,190,178,178,77,191,1,74]}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    
